[project]
name = "prose-metrics"
version = "0.2.0"
description = "Fast, deterministic, and modular prose & fiction analysis library in Python."
readme = "README.md"
license-files = ["LICENSE*"]
authors = [
    { name = "Aubin Septier" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "spacy>=3.8.15,<4.0",
    "textstat>=0.7.13,<0.8.0",
]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Intended Audience :: Developers",
	"Intended Audience :: Science/Research",
	"Topic :: Text Processing :: Linguistic",
	"Topic :: Software Development :: Libraries :: Python Modules",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: Implementation :: CPython",
	"Operating System :: OS Independent",
	"Typing :: Typed"
]

[tool.uv.build-backend]
module-root = ""
module-name = "prose_metrics"

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
fr-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.8.0/fr_core_news_sm-3.8.0-py3-none-any.whl" }

[build-system]
requires = ["uv_build>=0.11.33,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.17.0",
    "en-core-web-sm",
    "fr-core-news-sm",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "S",    # flake8-bandit
    "D",    # pydocstyle
    "ARG",  # flake8-unused-arguments
    "ANN",  # flake8-annotations
]
ignore = [
    "CPY001",
    "D413", # Blank line after last section
    "COM812",
    "N812",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "B010"]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.environment]
python-version = "3.12"

[tool.commitizen]
name = "cz_conventional_commits"
